version: '3.1'

services:

  jadio-httpd:
    image: httpd:2.4
    restart: always
    ports:
      - ${HTTPD_PORT}:80
    volumes:
      - ${MEDIA_ROOT}:/usr/local/apache2/htdocs/media:ro
      - ${RSS_ROOT}:/usr/local/apache2/htdocs/rss:ro

  jadio-feeder:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    shm_size: 2g
    environment:
      - BASE_URL=${BASE_URL}
      - MONGO_HOST=${MONGO_HOST}
    volumes:
      - ${MEDIA_ROOT}:/data/media:ro
      - ${RSS_ROOT}:/data/rss
